version: '3'

services:

  # Nginx will proxy requests to Nodejs server
  reverse-proxy:
    image: webasto-web:latest
    container_name: reverse_proxy_webasto-srv
    depends_on:
        - webasto-srv
    volumes:
      #- ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
      - /root/webasto-backend/saunagaming.com.pem:/root/webasto-backend/saunagaming.com.pem
      - /root/webasto-backend/saunagaming.com.key:/root/webasto-backend/saunagaming.com.key
    ports:
      - 80:80
    network_mode: "host"

  # Nodejs backend
  webasto-srv:
    image: webasto-srv:latest
    container_name: webasto-srv
    volumes:
      - /root/webasto-backend/ota:/app/ota
    ports:
      - 8080:8080
    network_mode: "host"
    restart: on-failure
    environment:
      - DOCKER_APP_PORT=8080
