version: '3'
services:

  # Nginx will proxy requests to Nodejs server
  reverse-proxy:
    build:
        context: ../webasto-web
        dockerfile: Dockerfile
    image: webasto-web:latest
    container_name: reverse_proxy_webasto-srv
    depends_on:
      - webasto-srv
    volumes:
      - /root/webasto-backend/saunagaming.com.pem:/root/webasto-backend/saunagaming.com.pem
      - /root/webasto-backend/saunagaming.com.key:/root/webasto-backend/saunagaming.com.key
    network_mode: "host"
    ports:
      - 80:80
      - 443:443
  # Nodejs backend
  webasto-srv:
    build:
        context: .
        dockerfile: Dockerfile
    image: webasto-srv:latest
    container_name: webasto-srv
    volumes:
      - /root/webasto-backend/ota:/app/ota
    network_mode: "host"
    ports:
      - 8080:8080
    restart: on-failure
    environment:
      - DOCKER_APP_PORT=8080

  # MySql server
  mysql-srv:
    build:
        context: ./mysql-docker
        dockerfile: Dockerfile
    image: webasto-mysql:latest
    container_name: webasto-mysql
    network_mode: "host"
    ports:
      - 3306:3306
    restart: on-failure
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - webasto-mysql:/var/lib/mysql
volumes:
    webasto-mysql:
