-- MySQL Script generated by MySQL Workbench
-- Fri Jul 22 16:39:29 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema webasto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema webasto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `webasto` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema old
-- -----------------------------------------------------
USE `webasto` ;

-- -----------------------------------------------------
-- Table `webasto`.`logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webasto`.`logs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `startTime` TIME NOT NULL,
  `endTime` TIME NOT NULL,
  `onTime` INT NOT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `webasto`.`statusData`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webasto`.`statusData` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` TINYINT(1) NOT NULL,
  `onTime` BIGINT UNSIGNED NOT NULL DEFAULT '15',
  `pulseSent` INT NOT NULL DEFAULT '0',
  `rssi` SMALLINT NULL DEFAULT NULL,
  `timestamp` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `webasto`.`tempData`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webasto`.`tempData` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `temperature` INT NOT NULL,
  `humidity` INT NOT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `webasto`.`timers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webasto`.`timers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `time` TIME NULL DEFAULT NULL,
  `time2` TIME NULL DEFAULT NULL,
  `enabled` TINYINT NOT NULL,
  `enabled2` TINYINT NOT NULL,
  `onTime` TINYINT UNSIGNED NOT NULL DEFAULT '30',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `webasto`.`uptime`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webasto`.`uptime` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uptime` FLOAT NOT NULL,
  `date` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `webasto`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webasto`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(30) NULL DEFAULT NULL,
  `password` VARCHAR(60) NULL DEFAULT NULL,
  `apikey` VARCHAR(255) NULL DEFAULT NULL,
  `secret` VARCHAR(32) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `webasto`.`voltageData`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webasto`.`voltageData` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `voltage` FLOAT NOT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `webasto`.`history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webasto`.`history` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `action` VARCHAR(60) NOT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ip` VARCHAR(20) NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_history_users_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_history_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `webasto`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
